### ISSUE TITLE
Give more feedback about results

### ISSUE THREAD

**Issue by levyj** [socrata/socrata-kettle#4]
It would be nice to get more feedback about the results of the Socrata Output step.  On failure, the reason is in the Kettle Log, which is not terrible but can be a bit hidden, given the verbose nature of Java errors.

On success, one gets **Job Status: SUCCESS** in the Log. Again, this is not terrible and one often does not need to know a lot more.

However, since DataSync does return a bit more detail in both cases, it would be nice to send it to the log and/or make it available in the stream for further use.  For example, the "Execute a process" step, which we use for our home-grown Data Sync execution, allows for capture of Result, Error, and Exit Value into the stream for further processing.

**Comment by malindac** [comment]
I have updated the plugin to display the full logging details of the DataSync job that runs.  Capturing the result for use further into the transformation will take some additional effort, but I believe it could be done.  If you have a chance to download the latest SocrataPlugin.zip file and let me know what you think, that would be very helpful!

Thanks,
Malinda

**Comment by levyj** [comment]
Where can I get it?  https://github.com/socrata/socrata-kettle/releases still shows the 10/2015 release.

Thanks.

Jon

**Comment by levyj** [comment]
Hi Malinda,

I remembered this on Friday. I am happy to take a look at the latest plugin. Where can I get it?

Thank you.

Jon

Jonathan Levy
Open Data Program Manager
(312) 744-2790
jonathan.levy@cityofchicago.org
data.cityofchicago.org
@JonOpenData

-----Original Message-----
From: Levy, Jonathan [Jonathan.Levy@cityofchicago.org]
Received: Friday, 15 Apr 2016, 3:53PM
To: socrata/socrata-kettle [reply@reply.github.com]
Subject: RE: [socrata/socrata-kettle] Give more feedback about results (#4)

Where can I get it?  https://github.com/socrata/socrata-kettle/releases still shows the 10/2015 release.

Thanks.

Jon
